### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by eauw** [lxfrdl/esmeralda#3]
Error:
```
swap gerit-sitemaps
Deleting alias 'gerit-sitemaps'.
Creating alias 'gerit-sitemaps' pointing to 'gerit-sitemaps-20190201145532'.
Deleting alias 'gerit-sitemaps-write'.
Found 7 index/indices matching 'gerit-lookups*':

Unhandled rejection TypeError: Cannot read property '0' of null
    at filterLastDays ([app]/node_modules/esmeralda/dist/utils.js:30:52)
    at [app]/node_modules/esmeralda/dist/esmeralda.js:112:14
    at tryCatcher ([app]/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler ([app]/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise ([app]/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 ([app]/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises ([app]/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep ([app]/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue ([app]/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues ([app]/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] ([app]/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

console.log('patternTimestamp',patternTimestamp.exec(index)) vor Zeile 30:
```
patternTimestamp [ '20190201133334',
  '20190201133334',
  index: 14,
  input: 'gerit-lookups-20190201133334',
  groups: undefined ]
patternTimestamp [ '20190201142023',
  '20190201142023',
  index: 14,
  input: 'gerit-lookups-20190201142023',
  groups: undefined ]
patternTimestamp null
```

**Comment by lxfrdl** [comment]
Fixed with https://github.com/lxfrdl/esmeralda/pull/4.
